name: publishing
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install npm dependencies
        run: yarn --frozen-lockfile
      - name: Publish package
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.OF_GITHUB_TOKEN }}
        run: |
          sed -i "s#react-native-webview#@open-fabric/react-native-webview#" ${GITHUB_WORKSPACE}/package.json
          yarn publish --no-git-tag-version --new-version $VERSION
      - name: Get version
        id: get_version
        run: echo "::set-output name=version::$(npm pkg get version 2> /dev/null | sed 's/\"//g')"
